pipeline {
    agent any

    stages {
        stage ('Stage 1 test') {

            
        }

        stage ('Testing Stage') {

            
        }


        stage ('Deployment Stage') {
            
        }
    }
}